/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLancamentoRouteImport } from './routes/_authenticated/lancamento'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPeriodosRouteImport } from './routes/_authenticated/periodos'
import { Route as AuthenticatedRegrasRouteImport } from './routes/_authenticated/regras'
import { Route as AuthenticatedAdminSplatRouteImport } from './routes/_authenticated/admin/$'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminCadastrosRouteImport } from './routes/_authenticated/admin/cadastros'
import { Route as AuthenticatedAuditoriasSplatRouteImport } from './routes/_authenticated/auditorias/$'
import { Route as AuthenticatedAvaliacoesSplatRouteImport } from './routes/_authenticated/avaliacoes/$'
import { Route as AuthenticatedBeneficiosSplatRouteImport } from './routes/_authenticated/beneficios/$'
import { Route as AuthenticatedKpiSplatRouteImport } from './routes/_authenticated/kpi/$'
import { Route as AuthenticatedOperacaoSplatRouteImport } from './routes/_authenticated/operacao/$'
import { Route as AuthenticatedRelatoriosSplatRouteImport } from './routes/_authenticated/relatorios/$'
import { Route as AuthenticatedTreinamentoSplatRouteImport } from './routes/_authenticated/treinamento/$'
import { Route as AuthenticatedRemuneracaoMensalLancamentosRouteImport } from './routes/_authenticated/remuneracao/mensal/lancamentos'
import { Route as AuthenticatedRemuneracaoMensalMetasRouteImport } from './routes/_authenticated/remuneracao/mensal/metas'
import { Route as AuthenticatedRemuneracaoMensalPainelRouteImport } from './routes/_authenticated/remuneracao/mensal/painel'
import { Route as AuthenticatedRemuneracaoMensalPeriodosRouteImport } from './routes/_authenticated/remuneracao/mensal/periodos'
import { Route as AuthenticatedRemuneracaoMensalRegrasRouteImport } from './routes/_authenticated/remuneracao/mensal/regras'
import { Route as AuthenticatedRemuneracaoPlrSplatRouteImport } from './routes/_authenticated/remuneracao/plr/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentoRoute = AuthenticatedLancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeriodosRoute = AuthenticatedPeriodosRouteImport.update({
  id: '/periodos',
  path: '/periodos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegrasRoute = AuthenticatedRegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSplatRoute = AuthenticatedAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCadastrosRoute =
  AuthenticatedAdminCadastrosRouteImport.update({
    id: '/admin/cadastros',
    path: '/admin/cadastros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriasSplatRoute =
  AuthenticatedAuditoriasSplatRouteImport.update({
    id: '/auditorias/$',
    path: '/auditorias/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliacoesSplatRoute =
  AuthenticatedAvaliacoesSplatRouteImport.update({
    id: '/avaliacoes/$',
    path: '/avaliacoes/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeneficiosSplatRoute =
  AuthenticatedBeneficiosSplatRouteImport.update({
    id: '/beneficios/$',
    path: '/beneficios/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKpiSplatRoute = AuthenticatedKpiSplatRouteImport.update({
  id: '/kpi/$',
  path: '/kpi/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacaoSplatRoute =
  AuthenticatedOperacaoSplatRouteImport.update({
    id: '/operacao/$',
    path: '/operacao/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosSplatRoute =
  AuthenticatedRelatoriosSplatRouteImport.update({
    id: '/relatorios/$',
    path: '/relatorios/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinamentoSplatRoute =
  AuthenticatedTreinamentoSplatRouteImport.update({
    id: '/treinamento/$',
    path: '/treinamento/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemuneracaoMensalLancamentosRoute =
  AuthenticatedRemuneracaoMensalLancamentosRouteImport.update({
    id: '/remuneracao/mensal/lancamentos',
    path: '/remuneracao/mensal/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemuneracaoMensalMetasRoute =
  AuthenticatedRemuneracaoMensalMetasRouteImport.update({
    id: '/remuneracao/mensal/metas',
    path: '/remuneracao/mensal/metas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemuneracaoMensalPainelRoute =
  AuthenticatedRemuneracaoMensalPainelRouteImport.update({
    id: '/remuneracao/mensal/painel',
    path: '/remuneracao/mensal/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemuneracaoMensalPeriodosRoute =
  AuthenticatedRemuneracaoMensalPeriodosRouteImport.update({
    id: '/remuneracao/mensal/periodos',
    path: '/remuneracao/mensal/periodos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemuneracaoMensalRegrasRoute =
  AuthenticatedRemuneracaoMensalRegrasRouteImport.update({
    id: '/remuneracao/mensal/regras',
    path: '/remuneracao/mensal/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemuneracaoPlrSplatRoute =
  AuthenticatedRemuneracaoPlrSplatRouteImport.update({
    id: '/remuneracao/plr/$',
    path: '/remuneracao/plr/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lancamento': typeof AuthenticatedLancamentoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/periodos': typeof AuthenticatedPeriodosRoute
  '/regras': typeof AuthenticatedRegrasRoute
  '/admin/$': typeof AuthenticatedAdminSplatRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/cadastros': typeof AuthenticatedAdminCadastrosRoute
  '/auditorias/$': typeof AuthenticatedAuditoriasSplatRoute
  '/avaliacoes/$': typeof AuthenticatedAvaliacoesSplatRoute
  '/beneficios/$': typeof AuthenticatedBeneficiosSplatRoute
  '/kpi/$': typeof AuthenticatedKpiSplatRoute
  '/operacao/$': typeof AuthenticatedOperacaoSplatRoute
  '/relatorios/$': typeof AuthenticatedRelatoriosSplatRoute
  '/treinamento/$': typeof AuthenticatedTreinamentoSplatRoute
  '/remuneracao/mensal/lancamentos': typeof AuthenticatedRemuneracaoMensalLancamentosRoute
  '/remuneracao/mensal/metas': typeof AuthenticatedRemuneracaoMensalMetasRoute
  '/remuneracao/mensal/painel': typeof AuthenticatedRemuneracaoMensalPainelRoute
  '/remuneracao/mensal/periodos': typeof AuthenticatedRemuneracaoMensalPeriodosRoute
  '/remuneracao/mensal/regras': typeof AuthenticatedRemuneracaoMensalRegrasRoute
  '/remuneracao/plr/$': typeof AuthenticatedRemuneracaoPlrSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lancamento': typeof AuthenticatedLancamentoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/periodos': typeof AuthenticatedPeriodosRoute
  '/regras': typeof AuthenticatedRegrasRoute
  '/admin/$': typeof AuthenticatedAdminSplatRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/cadastros': typeof AuthenticatedAdminCadastrosRoute
  '/auditorias/$': typeof AuthenticatedAuditoriasSplatRoute
  '/avaliacoes/$': typeof AuthenticatedAvaliacoesSplatRoute
  '/beneficios/$': typeof AuthenticatedBeneficiosSplatRoute
  '/kpi/$': typeof AuthenticatedKpiSplatRoute
  '/operacao/$': typeof AuthenticatedOperacaoSplatRoute
  '/relatorios/$': typeof AuthenticatedRelatoriosSplatRoute
  '/treinamento/$': typeof AuthenticatedTreinamentoSplatRoute
  '/remuneracao/mensal/lancamentos': typeof AuthenticatedRemuneracaoMensalLancamentosRoute
  '/remuneracao/mensal/metas': typeof AuthenticatedRemuneracaoMensalMetasRoute
  '/remuneracao/mensal/painel': typeof AuthenticatedRemuneracaoMensalPainelRoute
  '/remuneracao/mensal/periodos': typeof AuthenticatedRemuneracaoMensalPeriodosRoute
  '/remuneracao/mensal/regras': typeof AuthenticatedRemuneracaoMensalRegrasRoute
  '/remuneracao/plr/$': typeof AuthenticatedRemuneracaoPlrSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lancamento': typeof AuthenticatedLancamentoRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/periodos': typeof AuthenticatedPeriodosRoute
  '/_authenticated/regras': typeof AuthenticatedRegrasRoute
  '/_authenticated/admin/$': typeof AuthenticatedAdminSplatRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/cadastros': typeof AuthenticatedAdminCadastrosRoute
  '/_authenticated/auditorias/$': typeof AuthenticatedAuditoriasSplatRoute
  '/_authenticated/avaliacoes/$': typeof AuthenticatedAvaliacoesSplatRoute
  '/_authenticated/beneficios/$': typeof AuthenticatedBeneficiosSplatRoute
  '/_authenticated/kpi/$': typeof AuthenticatedKpiSplatRoute
  '/_authenticated/operacao/$': typeof AuthenticatedOperacaoSplatRoute
  '/_authenticated/relatorios/$': typeof AuthenticatedRelatoriosSplatRoute
  '/_authenticated/treinamento/$': typeof AuthenticatedTreinamentoSplatRoute
  '/_authenticated/remuneracao/mensal/lancamentos': typeof AuthenticatedRemuneracaoMensalLancamentosRoute
  '/_authenticated/remuneracao/mensal/metas': typeof AuthenticatedRemuneracaoMensalMetasRoute
  '/_authenticated/remuneracao/mensal/painel': typeof AuthenticatedRemuneracaoMensalPainelRoute
  '/_authenticated/remuneracao/mensal/periodos': typeof AuthenticatedRemuneracaoMensalPeriodosRoute
  '/_authenticated/remuneracao/mensal/regras': typeof AuthenticatedRemuneracaoMensalRegrasRoute
  '/_authenticated/remuneracao/plr/$': typeof AuthenticatedRemuneracaoPlrSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/auditoria'
    | '/cadastros'
    | '/dashboard'
    | '/lancamento'
    | '/metas'
    | '/painel'
    | '/periodos'
    | '/regras'
    | '/admin/$'
    | '/admin/auditoria'
    | '/admin/cadastros'
    | '/auditorias/$'
    | '/avaliacoes/$'
    | '/beneficios/$'
    | '/kpi/$'
    | '/operacao/$'
    | '/relatorios/$'
    | '/treinamento/$'
    | '/remuneracao/mensal/lancamentos'
    | '/remuneracao/mensal/metas'
    | '/remuneracao/mensal/painel'
    | '/remuneracao/mensal/periodos'
    | '/remuneracao/mensal/regras'
    | '/remuneracao/plr/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/auditoria'
    | '/cadastros'
    | '/dashboard'
    | '/lancamento'
    | '/metas'
    | '/painel'
    | '/periodos'
    | '/regras'
    | '/admin/$'
    | '/admin/auditoria'
    | '/admin/cadastros'
    | '/auditorias/$'
    | '/avaliacoes/$'
    | '/beneficios/$'
    | '/kpi/$'
    | '/operacao/$'
    | '/relatorios/$'
    | '/treinamento/$'
    | '/remuneracao/mensal/lancamentos'
    | '/remuneracao/mensal/metas'
    | '/remuneracao/mensal/painel'
    | '/remuneracao/mensal/periodos'
    | '/remuneracao/mensal/regras'
    | '/remuneracao/plr/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/auditoria'
    | '/_authenticated/cadastros'
    | '/_authenticated/dashboard'
    | '/_authenticated/lancamento'
    | '/_authenticated/metas'
    | '/_authenticated/painel'
    | '/_authenticated/periodos'
    | '/_authenticated/regras'
    | '/_authenticated/admin/$'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/cadastros'
    | '/_authenticated/auditorias/$'
    | '/_authenticated/avaliacoes/$'
    | '/_authenticated/beneficios/$'
    | '/_authenticated/kpi/$'
    | '/_authenticated/operacao/$'
    | '/_authenticated/relatorios/$'
    | '/_authenticated/treinamento/$'
    | '/_authenticated/remuneracao/mensal/lancamentos'
    | '/_authenticated/remuneracao/mensal/metas'
    | '/_authenticated/remuneracao/mensal/painel'
    | '/_authenticated/remuneracao/mensal/periodos'
    | '/_authenticated/remuneracao/mensal/regras'
    | '/_authenticated/remuneracao/plr/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamento': {
      id: '/_authenticated/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof AuthenticatedLancamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/periodos': {
      id: '/_authenticated/periodos'
      path: '/periodos'
      fullPath: '/periodos'
      preLoaderRoute: typeof AuthenticatedPeriodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regras': {
      id: '/_authenticated/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof AuthenticatedRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$': {
      id: '/_authenticated/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AuthenticatedAdminSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cadastros': {
      id: '/_authenticated/admin/cadastros'
      path: '/admin/cadastros'
      fullPath: '/admin/cadastros'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditorias/$': {
      id: '/_authenticated/auditorias/$'
      path: '/auditorias/$'
      fullPath: '/auditorias/$'
      preLoaderRoute: typeof AuthenticatedAuditoriasSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes/$': {
      id: '/_authenticated/avaliacoes/$'
      path: '/avaliacoes/$'
      fullPath: '/avaliacoes/$'
      preLoaderRoute: typeof AuthenticatedAvaliacoesSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beneficios/$': {
      id: '/_authenticated/beneficios/$'
      path: '/beneficios/$'
      fullPath: '/beneficios/$'
      preLoaderRoute: typeof AuthenticatedBeneficiosSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kpi/$': {
      id: '/_authenticated/kpi/$'
      path: '/kpi/$'
      fullPath: '/kpi/$'
      preLoaderRoute: typeof AuthenticatedKpiSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/$': {
      id: '/_authenticated/operacao/$'
      path: '/operacao/$'
      fullPath: '/operacao/$'
      preLoaderRoute: typeof AuthenticatedOperacaoSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/$': {
      id: '/_authenticated/relatorios/$'
      path: '/relatorios/$'
      fullPath: '/relatorios/$'
      preLoaderRoute: typeof AuthenticatedRelatoriosSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinamento/$': {
      id: '/_authenticated/treinamento/$'
      path: '/treinamento/$'
      fullPath: '/treinamento/$'
      preLoaderRoute: typeof AuthenticatedTreinamentoSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remuneracao/mensal/lancamentos': {
      id: '/_authenticated/remuneracao/mensal/lancamentos'
      path: '/remuneracao/mensal/lancamentos'
      fullPath: '/remuneracao/mensal/lancamentos'
      preLoaderRoute: typeof AuthenticatedRemuneracaoMensalLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remuneracao/mensal/metas': {
      id: '/_authenticated/remuneracao/mensal/metas'
      path: '/remuneracao/mensal/metas'
      fullPath: '/remuneracao/mensal/metas'
      preLoaderRoute: typeof AuthenticatedRemuneracaoMensalMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remuneracao/mensal/painel': {
      id: '/_authenticated/remuneracao/mensal/painel'
      path: '/remuneracao/mensal/painel'
      fullPath: '/remuneracao/mensal/painel'
      preLoaderRoute: typeof AuthenticatedRemuneracaoMensalPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remuneracao/mensal/periodos': {
      id: '/_authenticated/remuneracao/mensal/periodos'
      path: '/remuneracao/mensal/periodos'
      fullPath: '/remuneracao/mensal/periodos'
      preLoaderRoute: typeof AuthenticatedRemuneracaoMensalPeriodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remuneracao/mensal/regras': {
      id: '/_authenticated/remuneracao/mensal/regras'
      path: '/remuneracao/mensal/regras'
      fullPath: '/remuneracao/mensal/regras'
      preLoaderRoute: typeof AuthenticatedRemuneracaoMensalRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remuneracao/plr/$': {
      id: '/_authenticated/remuneracao/plr/$'
      path: '/remuneracao/plr/$'
      fullPath: '/remuneracao/plr/$'
      preLoaderRoute: typeof AuthenticatedRemuneracaoPlrSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLancamentoRoute: typeof AuthenticatedLancamentoRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPeriodosRoute: typeof AuthenticatedPeriodosRoute
  AuthenticatedRegrasRoute: typeof AuthenticatedRegrasRoute
  AuthenticatedAdminSplatRoute: typeof AuthenticatedAdminSplatRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminCadastrosRoute: typeof AuthenticatedAdminCadastrosRoute
  AuthenticatedAuditoriasSplatRoute: typeof AuthenticatedAuditoriasSplatRoute
  AuthenticatedAvaliacoesSplatRoute: typeof AuthenticatedAvaliacoesSplatRoute
  AuthenticatedBeneficiosSplatRoute: typeof AuthenticatedBeneficiosSplatRoute
  AuthenticatedKpiSplatRoute: typeof AuthenticatedKpiSplatRoute
  AuthenticatedOperacaoSplatRoute: typeof AuthenticatedOperacaoSplatRoute
  AuthenticatedRelatoriosSplatRoute: typeof AuthenticatedRelatoriosSplatRoute
  AuthenticatedTreinamentoSplatRoute: typeof AuthenticatedTreinamentoSplatRoute
  AuthenticatedRemuneracaoMensalLancamentosRoute: typeof AuthenticatedRemuneracaoMensalLancamentosRoute
  AuthenticatedRemuneracaoMensalMetasRoute: typeof AuthenticatedRemuneracaoMensalMetasRoute
  AuthenticatedRemuneracaoMensalPainelRoute: typeof AuthenticatedRemuneracaoMensalPainelRoute
  AuthenticatedRemuneracaoMensalPeriodosRoute: typeof AuthenticatedRemuneracaoMensalPeriodosRoute
  AuthenticatedRemuneracaoMensalRegrasRoute: typeof AuthenticatedRemuneracaoMensalRegrasRoute
  AuthenticatedRemuneracaoPlrSplatRoute: typeof AuthenticatedRemuneracaoPlrSplatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLancamentoRoute: AuthenticatedLancamentoRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPeriodosRoute: AuthenticatedPeriodosRoute,
  AuthenticatedRegrasRoute: AuthenticatedRegrasRoute,
  AuthenticatedAdminSplatRoute: AuthenticatedAdminSplatRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminCadastrosRoute: AuthenticatedAdminCadastrosRoute,
  AuthenticatedAuditoriasSplatRoute: AuthenticatedAuditoriasSplatRoute,
  AuthenticatedAvaliacoesSplatRoute: AuthenticatedAvaliacoesSplatRoute,
  AuthenticatedBeneficiosSplatRoute: AuthenticatedBeneficiosSplatRoute,
  AuthenticatedKpiSplatRoute: AuthenticatedKpiSplatRoute,
  AuthenticatedOperacaoSplatRoute: AuthenticatedOperacaoSplatRoute,
  AuthenticatedRelatoriosSplatRoute: AuthenticatedRelatoriosSplatRoute,
  AuthenticatedTreinamentoSplatRoute: AuthenticatedTreinamentoSplatRoute,
  AuthenticatedRemuneracaoMensalLancamentosRoute:
    AuthenticatedRemuneracaoMensalLancamentosRoute,
  AuthenticatedRemuneracaoMensalMetasRoute:
    AuthenticatedRemuneracaoMensalMetasRoute,
  AuthenticatedRemuneracaoMensalPainelRoute:
    AuthenticatedRemuneracaoMensalPainelRoute,
  AuthenticatedRemuneracaoMensalPeriodosRoute:
    AuthenticatedRemuneracaoMensalPeriodosRoute,
  AuthenticatedRemuneracaoMensalRegrasRoute:
    AuthenticatedRemuneracaoMensalRegrasRoute,
  AuthenticatedRemuneracaoPlrSplatRoute: AuthenticatedRemuneracaoPlrSplatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
